[project]
name = "sprint-03-menu-generator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.0.7",
    "langchain-openai>=1.0.3",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.44",
]
